### ISSUE TITLE
Is there a specific experiment video?

### ISSUE THREAD

**Issue by hr2894235132** [engcang/FAST-LIO-Localization-QN#2]
Thank you for your excellent work, it would be nice to have a specific experiment video。

**Comment by engcang** [comment]
Hi @hr2894235132 

You can watch the temporal experiment video here - https://youtu.be/b8t5ZwC4xZw, which I used KITTI 05 seq.
White, green, and red pointclouds represent saved map, matched, and source for matching, respectively.
The blue circles and trajectory are from odometry (FAST-LIO2) and green ones are the corrected with localization.

But sadly, as I mentioned in [this issue](https://github.com/engcang/FAST-LIO-Localization-QN/issues/1), the experiment is also done with `Quatro` disabled at this moment. 
Let me tell you when the downsampling is done :)

**Comment by hr2894235132** [comment]
> Hi @hr2894235132
> 
> You can watch the temporal experiment video here - https://youtu.be/b8t5ZwC4xZw, which I used KITTI 05 seq. White, green, and red pointclouds represent saved map, matched, and source for matching, respectively. The blue circles and trajectory are from odometry (FAST-LIO2) and green ones are the corrected with localization.
> 
> But sadly, as I mentioned in [this issue](https://github.com/engcang/FAST-LIO-Localization-QN/issues/1), the experiment is also done with `Quatro` disabled at this moment. Let me tell you when the downsampling is done :)

Thank you very much for your reply！

**Comment by hr2894235132** [comment]
> Hi @hr2894235132
> 
> You can watch the temporal experiment video here - https://youtu.be/b8t5ZwC4xZw, which I used KITTI 05 seq. White, green, and red pointclouds represent saved map, matched, and source for matching, respectively. The blue circles and trajectory are from odometry (FAST-LIO2) and green ones are the corrected with localization.
> 
> But sadly, as I mentioned in [this issue](https://github.com/engcang/FAST-LIO-Localization-QN/issues/1), the experiment is also done with `Quatro` disabled at this moment. Let me tell you when the downsampling is done :)

Hello, before using this positioning package, must I save the package containing "/keyframe_pcd" and "/keyframe_pose" in advance? For example, in fast-lio2, if I only save the pcd file of the point cloud, it is not possible, right?

**Comment by engcang** [comment]
@hr2894235132 
Exactly. Only saving .pcd file does not work with this package.
I can also implement that functional, but then ICP matching should be done between current scan and radius-searched pointcloud from the pcd file and I think that is inefficient.

**Comment by hr2894235132** [comment]
> @hr2894235132 Exactly. Only saving .pcd file does not work with this package. I can also implement that functional, but then ICP matching should be done between current scan and radius-searched pointcloud from the pcd file and I think that is inefficient.

Thank you very much for your reply！
You're right, I've used this normal ICP to match the current scan with the point cloud in the cut PCD file.
This method I had to manually give the initial pose. I see that the initial pose is not provided in FAST-LIO-Localization-QN, does your method not rely on the initial pose?
In addition, if I see that you mentioned that you can use FAST-LIO-SAM-QN to save offline map files, then I can also save it with dlio? dlio also seems to use nano_gicp to match.

**Comment by engcang** [comment]
Hi @hr2894235132 

1. It relies on the initial pose. The re-starting initial pose should be close enough to the first-started initial pose of the saved .bag file. This package is mainly designed and developed for indoor autonomous patrol robot which usually starts the service from the almost same initial pose. I found the translational displacement is not that big problem, so you can start few meters away. But, rotational displacement is the problem. 
2. No matter what package you use, just save the time synchronized pointcloud and odometry as FAST-LIO-SAM-QN does.

**Comment by hr2894235132** [comment]
> 2\. FAST-LIO-SAM-QN

Thank you for your patience and reply！ I'll give it a try.
Also, I'm having a bit of a problem trying to use FAST-LIO-SAM-QN with the livox avia dataset.(https://github.com/engcang/FAST-LIO-SAM-QN/issues/2)
