### ISSUE TITLE
Any localization with sc + qn

### ISSUE THREAD

**Issue by mini-1235** [engcang/FAST-LIO-Localization-QN#3]
I found that there is a version for sc + qn and another with only qn when mapping, is there any sc + qn version for localization? Also, is there any plan to migrate to ROS2

**Comment by engcang** [comment]
@mini-1235 Hi.
There is no SC+QN version for localization yet, but I think I can implement it easily, If I have time...
The same goes for the ROS2 version.

I will let you know when I implement them.

**Comment by engcang** [comment]
@mini-1235 I implemented the ScanContext added version. Check out here - https://github.com/engcang/FAST-LIO-Localization-SC-QN

**Comment by mini-1235** [comment]
Thank you!
