### ISSUE TITLE
How can I record the data rosbag with FAST-LIO-SAM-QN

### ISSUE THREAD

**Issue by ayane11** [engcang/FAST-LIO-Localization-QN#4]
How can I record the data rosbag with FAST-LIO-SAM-QN, when I finish building the map, I got PCD file, but I don't know How can I get the rosbag file that can be used in FAST-LIO-Localization-QN and FAST-LIO-Localization-SC-QN

**Comment by engcang** [comment]
@Ayane11 
Hey!

Set these lines as true: https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/config/config.yaml#L43-L44
Then, the code saves the bag file when you finish the FAST-LIO-SAM-QN at here: https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/src/constructor.cpp#L123-L139

Specifically, you can find the result.bag file at the package root directory, i.e., 
```sh
roscd fast_lio_sam_qn
ls result.bag #you can find the bag file here.
rosbag info result.bag
```
