### ISSUE TITLE
Dose this project support Mid-360 lidar?

### ISSUE THREAD

**Issue by JACKLiuDay** [engcang/FAST-LIO-Localization-QN#5]
Hi, thank you for your open-sourced project. Does this project support Mid-360 lidar? Additionally, what is the output frequency of the odometry that can be achieved by the map-based localization method? After all, localization information with a very low frequency cannot be used.

**Comment by engcang** [comment]
Hi @JACKLiuDay 
1. Yes MID-360 LiDAR can be used.
2. It should be same with the frequency of the input LiDAR, but it depends on the third party odometry package - FAST-LIO2. Basically it can output the odometry in real time.
3. Very low frequency LiDAR input may not be enough to estimate odometry in the third party package (FAST-LIO2) and also in this package's localization, as it depends on the Quatro and Nano-GICP to match and calculate the relative pose between the map and the current scan. There should be enough overlapping pointclouds between the map and the input scan.

**Comment by JACKLiuDay** [comment]
> Hi @JACKLiuDay
> 
> 1. Yes MID-360 LiDAR can be used.
> 2. It should be same with the frequency of the input LiDAR, but it depends on the third party odometry package - FAST-LIO2. Basically it can output the odometry in real time.
> 3. Very low frequency LiDAR input may not be enough to estimate odometry in the third party package (FAST-LIO2) and also in this package's localization, as it depends on the Quatro and Nano-GICP to match and calculate the relative pose between the map and the current scan. There should be enough overlapping pointclouds between the map and the input scan.

Thank you very much for your quick response. We will try to use mid360 to replicate the project.

**Comment by WheresWes** [comment]
@JACKLiuDay I am curious as to how you got on with your mid 360. I have the same scanner and I am interested to try this project
